- name: Install fail2ban
  apt: pkg=fail2ban state=latest
- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades state=latest
- name: Install logwatch
  apt: pkg=logwatch state=latest
- name: Add default user
  user: name="{{ security.user_login }}"
- name: Set user password
  shell: "echo \"{{ security.user_login }}:{{ security.user_password }}\" | chpasswd"
- name: Create user .ssh directory
  file: path="~{{ security.user_login }}/.ssh" mode=0700 state=directory owner="{{ security.user_login }}"
- name: Create user authorized_keys
  template: src=roles/security/templates/authorized_keys.j2 dest="~{{ security.user_login }}/.ssh/authorized_keys" owner="{{ security.user_login }}" mode=0400
- name: "/etc/sudoers"
  template: src=roles/security/templates/sudoers.j2 dest=/etc/sudoers
- name: "/etc/ssh/sshd_config: PermitRootLogin no"
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no"
- name: "/etc/ssh/sshd_config: PasswordAuthentication no"
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no"
- name: Restart SSHD
  service: state=restarted name=ssh
- name: "/etc/apt/apt.conf.d/10periodic"
  template: src=roles/security/templates/unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/10periodic
- name: "/etc/cron.daily/00logwatch"
  lineinfile: dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto {{ security.email }} --detail high"
- name: "Create local jail for fail2ban"
  shell: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
- name: "/etc/fail2ban/jail.local - security email"
  lineinfile: dest=/etc/fail2ban/jail.local regexp="^#?s*destemail\s*=" line="destemail = {{ security.email }}"
- name: "/etc/fail2ban/jail.local - enable emails"
  lineinfile: dest=/etc/fail2ban/jail.local regexp="^#?s*action\s*=\s*\%\(action_" line="action = %(action_mwl)s"
- name: "/etc/fail2ban/jail.local - enable ssh watcher"
  replace: dest=/etc/fail2ban/jail.local regexp="\[ssh\]\n*enabled\s*=[^\n]*" replace="[ssh]\n\nenabled = true"
- name: "/etc/fail2ban/jail.local - enable ssh-ddos watcher"
  replace: dest=/etc/fail2ban/jail.local regexp="\[ssh-ddos\]\n*enabled\s*=[^\n]*" replace="[ssh-ddos]\n\nenabled = true"
- name: "/etc/fail2ban/jail.local - enable nginx-http-auth watcher"
  replace: dest=/etc/fail2ban/jail.local regexp="\[nginx-http-auth\]\n*enabled\s*=[^\n]*" replace="[nginx-http-auth]\n\nenabled = true"
- name: "/etc/fail2ban/jail.local - enable postfix watcher"
  replace: dest=/etc/fail2ban/jail.local regexp="\[postfix\]\n*enabled\s*=[^\n]*" replace="[postfix]\n\nenabled = true"
- name: "/etc/fail2ban/jail.local - enable dovecot watcher"
  replace: dest=/etc/fail2ban/jail.local regexp="\[dovecot\]\n*enabled\s*=[^\n]*" replace="[dovecot]\n\nenabled = true"
- name: "/etc/fail2ban/jail.local - enable recidive watcher"
  replace: dest=/etc/fail2ban/jail.local regexp="\[recidive\]\n*enabled\s*=[^\n]*" replace="[recidive]\n\nenabled = true"

